@ECHO OFF

SET HC_VRTrial_GAME_DATA_DIR=%HC_VRTrial_GAME_HOME%\HoneyCome_Data
SET HC_VRTrial_SOLUTION_DIR=%CD%\..
SET HC_VRTrial_DEBUG_OUTPUT_DIR=%HC_VRTrial_SOLUTION_DIR%\HC_VRTrial\bin\Debug\net6.0
SET HC_VRTrial_RELEASE_OUTPUT_DIR=%HC_VRTrial_SOLUTION_DIR%\HC_VRTrial\bin\Release\net6.0
SET HC_VRTrial_PACKAGE_DIR=%CD%\package
